Plugins:
  griefPreventionPlus: true
  factions: false
  witchery: false
Events:
  griefPreventionPlus:
    claimCreate: true
    claimDelte: true
    claimEnter: true
    claimExit: true
  factions:
    factionCreate: true
    factionDisband: true
  witchery:
    tagLock: false